import MessageBlock from "../components/MessageBlock";
import "../styles/Home.css";

const messages = [
  {
    user: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce vel massa rutrum, sagittis mauris et, vehicula odio. Mauris pellentesque facilisis diam et venenatis. Nullam pharetra placerat ante sit amet suscipit. Donec ut dolor sollicitudin, commodo ipsum eget, lacinia nulla. Integer turpis mi, vulputate et pretium ut, finibus malesuada purus. Nullam sed placerat odio, quis luctus ex. Aliquam laoreet turpis eget magna cursus, ac bibendum eros suscipit. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed auctor nisi velit, scelerisque semper leo iaculis at. Quisque vitae dolor vehicula, placerat metus nec, laoreet erat. Praesent malesuada rutrum nibh, sed auctor purus lobortis vel. Aliquam non augue massa. Morbi laoreet tellus a quam fringilla, ut tempor felis cursus.",
    ai: "In viverra ornare nibh, in venenatis nulla venenatis ut. Nullam odio tortor, congue sit amet feugiat et, ornare quis metus. Ut rhoncus sit amet est sit amet lacinia. In quis ornare nulla. Proin scelerisque, dui vitae placerat imperdiet, lacus lectus auctor risus, interdum efficitur ipsum orci sit amet lacus. Donec auctor diam erat, sed scelerisque risus posuere a. In sodales lorem sed elementum rutrum. Proin eget condimentum est, ut elementum elit.",
  },
  {
    user: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce vel massa rutrum, sagittis mauris et, vehicula odio. Mauris pellentesque facilisis diam et venenatis. Nullam pharetra placerat ante sit amet suscipit. Donec ut dolor sollicitudin, commodo ipsum eget, lacinia nulla. Integer turpis mi, vulputate et pretium ut, finibus malesuada purus. Nullam sed placerat odio, quis luctus ex. Aliquam laoreet turpis eget magna cursus, ac bibendum eros suscipit. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed auctor nisi velit, scelerisque semper leo iaculis at. Quisque vitae dolor vehicula, placerat metus nec, laoreet erat. Praesent malesuada rutrum nibh, sed auctor purus lobortis vel. Aliquam non augue massa. Morbi laoreet tellus a quam fringilla, ut tempor felis cursus.",
    ai: "In viverra ornare nibh, in venenatis nulla venenatis ut. Nullam odio tortor, congue sit amet feugiat et, ornare quis metus. Ut rhoncus sit amet est sit amet lacinia. In quis ornare nulla. Proin scelerisque, dui vitae placerat imperdiet, lacus lectus auctor risus, interdum efficitur ipsum orci sit amet lacus. Donec auctor diam erat, sed scelerisque risus posuere a. In sodales lorem sed elementum rutrum. Proin eget condimentum est, ut elementum elit.",
  },
  {
    user: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce vel massa rutrum, sagittis mauris et, vehicula odio. Mauris pellentesque facilisis diam et venenatis. Nullam pharetra placerat ante sit amet suscipit. Donec ut dolor sollicitudin, commodo ipsum eget, lacinia nulla. Integer turpis mi, vulputate et pretium ut, finibus malesuada purus. Nullam sed placerat odio, quis luctus ex. Aliquam laoreet turpis eget magna cursus, ac bibendum eros suscipit. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed auctor nisi velit, scelerisque semper leo iaculis at. Quisque vitae dolor vehicula, placerat metus nec, laoreet erat. Praesent malesuada rutrum nibh, sed auctor purus lobortis vel. Aliquam non augue massa. Morbi laoreet tellus a quam fringilla, ut tempor felis cursus.",
    ai: "In viverra ornare nibh, in venenatis nulla venenatis ut. Nullam odio tortor, congue sit amet feugiat et, ornare quis metus. Ut rhoncus sit amet est sit amet lacinia. In quis ornare nulla. Proin scelerisque, dui vitae placerat imperdiet, lacus lectus auctor risus, interdum efficitur ipsum orci sit amet lacus. Donec auctor diam erat, sed scelerisque risus posuere a. In sodales lorem sed elementum rutrum. Proin eget condimentum est, ut elementum elit.",
  },
  {
    user: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce vel massa rutrum, sagittis mauris et, vehicula odio. Mauris pellentesque facilisis diam et venenatis. Nullam pharetra placerat ante sit amet suscipit. Donec ut dolor sollicitudin, commodo ipsum eget, lacinia nulla. Integer turpis mi, vulputate et pretium ut, finibus malesuada purus. Nullam sed placerat odio, quis luctus ex. Aliquam laoreet turpis eget magna cursus, ac bibendum eros suscipit. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed auctor nisi velit, scelerisque semper leo iaculis at. Quisque vitae dolor vehicula, placerat metus nec, laoreet erat. Praesent malesuada rutrum nibh, sed auctor purus lobortis vel. Aliquam non augue massa. Morbi laoreet tellus a quam fringilla, ut tempor felis cursus.",
    ai: "In viverra ornare nibh, in venenatis nulla venenatis ut. Nullam odio tortor, congue sit amet feugiat et, ornare quis metus. Ut rhoncus sit amet est sit amet lacinia. In quis ornare nulla. Proin scelerisque, dui vitae placerat imperdiet, lacus lectus auctor risus, interdum efficitur ipsum orci sit amet lacus. Donec auctor diam erat, sed scelerisque risus posuere a. In sodales lorem sed elementum rutrum. Proin eget condimentum est, ut elementum elit.",
  },
  {
    user: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce vel massa rutrum, sagittis mauris et, vehicula odio. Mauris pellentesque facilisis diam et venenatis. Nullam pharetra placerat ante sit amet suscipit. Donec ut dolor sollicitudin, commodo ipsum eget, lacinia nulla. Integer turpis mi, vulputate et pretium ut, finibus malesuada purus. Nullam sed placerat odio, quis luctus ex. Aliquam laoreet turpis eget magna cursus, ac bibendum eros suscipit. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed auctor nisi velit, scelerisque semper leo iaculis at. Quisque vitae dolor vehicula, placerat metus nec, laoreet erat. Praesent malesuada rutrum nibh, sed auctor purus lobortis vel. Aliquam non augue massa. Morbi laoreet tellus a quam fringilla, ut tempor felis cursus.",
    ai: "In viverra ornare nibh, in venenatis nulla venenatis ut. Nullam odio tortor, congue sit amet feugiat et, ornare quis metus. Ut rhoncus sit amet est sit amet lacinia. In quis ornare nulla. Proin scelerisque, dui vitae placerat imperdiet, lacus lectus auctor risus, interdum efficitur ipsum orci sit amet lacus. Donec auctor diam erat, sed scelerisque risus posuere a. In sodales lorem sed elementum rutrum. Proin eget condimentum est, ut elementum elit.",
  },
  {
    user: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce vel massa rutrum, sagittis mauris et, vehicula odio. Mauris pellentesque facilisis diam et venenatis. Nullam pharetra placerat ante sit amet suscipit. Donec ut dolor sollicitudin, commodo ipsum eget, lacinia nulla. Integer turpis mi, vulputate et pretium ut, finibus malesuada purus. Nullam sed placerat odio, quis luctus ex. Aliquam laoreet turpis eget magna cursus, ac bibendum eros suscipit. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed auctor nisi velit, scelerisque semper leo iaculis at. Quisque vitae dolor vehicula, placerat metus nec, laoreet erat. Praesent malesuada rutrum nibh, sed auctor purus lobortis vel. Aliquam non augue massa. Morbi laoreet tellus a quam fringilla, ut tempor felis cursus.",
    ai: "In viverra ornare nibh, in venenatis nulla venenatis ut. Nullam odio tortor, congue sit amet feugiat et, ornare quis metus. Ut rhoncus sit amet est sit amet lacinia. In quis ornare nulla. Proin scelerisque, dui vitae placerat imperdiet, lacus lectus auctor risus, interdum efficitur ipsum orci sit amet lacus. Donec auctor diam erat, sed scelerisque risus posuere a. In sodales lorem sed elementum rutrum. Proin eget condimentum est, ut elementum elit.",
  },
  {
    user: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce vel massa rutrum, sagittis mauris et, vehicula odio. Mauris pellentesque facilisis diam et venenatis. Nullam pharetra placerat ante sit amet suscipit. Donec ut dolor sollicitudin, commodo ipsum eget, lacinia nulla. Integer turpis mi, vulputate et pretium ut, finibus malesuada purus. Nullam sed placerat odio, quis luctus ex. Aliquam laoreet turpis eget magna cursus, ac bibendum eros suscipit. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed auctor nisi velit, scelerisque semper leo iaculis at. Quisque vitae dolor vehicula, placerat metus nec, laoreet erat. Praesent malesuada rutrum nibh, sed auctor purus lobortis vel. Aliquam non augue massa. Morbi laoreet tellus a quam fringilla, ut tempor felis cursus.",
    ai: "In viverra ornare nibh, in venenatis nulla venenatis ut. Nullam odio tortor, congue sit amet feugiat et, ornare quis metus. Ut rhoncus sit amet est sit amet lacinia. In quis ornare nulla. Proin scelerisque, dui vitae placerat imperdiet, lacus lectus auctor risus, interdum efficitur ipsum orci sit amet lacus. Donec auctor diam erat, sed scelerisque risus posuere a. In sodales lorem sed elementum rutrum. Proin eget condimentum est, ut elementum elit.",
  },
  {
    user: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce vel massa rutrum, sagittis mauris et, vehicula odio. Mauris pellentesque facilisis diam et venenatis. Nullam pharetra placerat ante sit amet suscipit. Donec ut dolor sollicitudin, commodo ipsum eget, lacinia nulla. Integer turpis mi, vulputate et pretium ut, finibus malesuada purus. Nullam sed placerat odio, quis luctus ex. Aliquam laoreet turpis eget magna cursus, ac bibendum eros suscipit. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed auctor nisi velit, scelerisque semper leo iaculis at. Quisque vitae dolor vehicula, placerat metus nec, laoreet erat. Praesent malesuada rutrum nibh, sed auctor purus lobortis vel. Aliquam non augue massa. Morbi laoreet tellus a quam fringilla, ut tempor felis cursus.",
    ai: "In viverra ornare nibh, in venenatis nulla venenatis ut. Nullam odio tortor, congue sit amet feugiat et, ornare quis metus. Ut rhoncus sit amet est sit amet lacinia. In quis ornare nulla. Proin scelerisque, dui vitae placerat imperdiet, lacus lectus auctor risus, interdum efficitur ipsum orci sit amet lacus. Donec auctor diam erat, sed scelerisque risus posuere a. In sodales lorem sed elementum rutrum. Proin eget condimentum est, ut elementum elit.",
  },
  {
    user: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce vel massa rutrum, sagittis mauris et, vehicula odio. Mauris pellentesque facilisis diam et venenatis. Nullam pharetra placerat ante sit amet suscipit. Donec ut dolor sollicitudin, commodo ipsum eget, lacinia nulla. Integer turpis mi, vulputate et pretium ut, finibus malesuada purus. Nullam sed placerat odio, quis luctus ex. Aliquam laoreet turpis eget magna cursus, ac bibendum eros suscipit. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed auctor nisi velit, scelerisque semper leo iaculis at. Quisque vitae dolor vehicula, placerat metus nec, laoreet erat. Praesent malesuada rutrum nibh, sed auctor purus lobortis vel. Aliquam non augue massa. Morbi laoreet tellus a quam fringilla, ut tempor felis cursus.",
    ai: "In viverra ornare nibh, in venenatis nulla venenatis ut. Nullam odio tortor, congue sit amet feugiat et, ornare quis metus. Ut rhoncus sit amet est sit amet lacinia. In quis ornare nulla. Proin scelerisque, dui vitae placerat imperdiet, lacus lectus auctor risus, interdum efficitur ipsum orci sit amet lacus. Donec auctor diam erat, sed scelerisque risus posuere a. In sodales lorem sed elementum rutrum. Proin eget condimentum est, ut elementum elit.",
  },
  {
    user: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce vel massa rutrum, sagittis mauris et, vehicula odio. Mauris pellentesque facilisis diam et venenatis. Nullam pharetra placerat ante sit amet suscipit. Donec ut dolor sollicitudin, commodo ipsum eget, lacinia nulla. Integer turpis mi, vulputate et pretium ut, finibus malesuada purus. Nullam sed placerat odio, quis luctus ex. Aliquam laoreet turpis eget magna cursus, ac bibendum eros suscipit. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed auctor nisi velit, scelerisque semper leo iaculis at. Quisque vitae dolor vehicula, placerat metus nec, laoreet erat. Praesent malesuada rutrum nibh, sed auctor purus lobortis vel. Aliquam non augue massa. Morbi laoreet tellus a quam fringilla, ut tempor felis cursus.",
    ai: "In viverra ornare nibh, in venenatis nulla venenatis ut. Nullam odio tortor, congue sit amet feugiat et, ornare quis metus. Ut rhoncus sit amet est sit amet lacinia. In quis ornare nulla. Proin scelerisque, dui vitae placerat imperdiet, lacus lectus auctor risus, interdum efficitur ipsum orci sit amet lacus. Donec auctor diam erat, sed scelerisque risus posuere a. In sodales lorem sed elementum rutrum. Proin eget condimentum est, ut elementum elit.",
  },
];

export default function Home() {
  return (
    <div className="home">
      <div className="chat-header">
        <div>ChatAI</div>
      </div>
      <div className="message-area">
        {messages.map((item) => (
          <MessageBlock message={item} />
        ))}
      </div>
      <div className="chat-footer">
        <input />
        <button>Send</button>
      </div>
    </div>
  );
}
